version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: sifm-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: sifm  # Alterado de 'postgres' para 'sifm'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  backend:
    build: .
    container_name: sifm-backend
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:123456@postgres:5432/sifm
      JWT_SECRET: supersecreto123456789
    ports:
      - "3002:3002"  # Alterado para a porta 3001 que vocÃª estava usando
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data: